### ISSUE TITLE
I can't find and can't run twitterr

### ISSUE THREAD

**Issue by jandy12bedoya** [KorbsStudio/Twitterr#1]
First install Twitterr by snapd and the application did not appear in the app center, I tried to run it from the terminal and it said "order not found". I uninstalled, reinstalled and the same.

I uninstalled again and install as recommended here and sequence exactly the same.

All this in Elementary OS latest version.

**Comment by SuperZoops** [comment]
Same issue on Arch.
Across multiple releases.

**Comment by zalloy** [comment]
I'm having the same problem on Kubuntu 20.04

**Comment by KorbsStudio** [comment]
This has been tested on Ubuntu, Zorin, Deepin, and mostly Elementary OS.
As for Arch, not sure how that will work out.

**Comment by KorbsStudio** [comment]
Also Twitterr is on Snap, but does not work.
I recommend just using the installer I already made.

**Comment by KorbsStudio** [comment]
The install script will download and add Twitterr to /usr/share/twitterr/ I think.
So just find that and use `./Twitter` in the terminal or `./twitterr`.
