### ISSUE TITLE
Site 403

### ISSUE THREAD

**Issue by GreenMan36** [KorbsStudio/Twitterr#5]
https://twitterr.korbsstudio.com/ returns 403 Forbidden

**Comment by KorbsStudio** [comment]
The project isn't really active anymore.
Use release section of the repo.

**Comment by KorbsStudio** [comment]
Revival is happening

**Comment by KorbsStudio** [comment]
Returned: https://twitterish.korbsstudio.com/
Some new stuff is still being added to the application, so the app isn't available yet.
